[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://yitszskqhbtuplwotgon.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_kGVUjQWRFyPSavfHp309Vg_ObSw2ifj"

[[plugins]]
  package = "@netlify/plugin-nextjs"
